services:
  server:
    image: "nginx:1.26.1-alpine"
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    extra_hosts:
        - "host.docker.internal:host-gateway"
    depends_on:
      - php 
    networks:
      - ptd-network
  php:
    build:
      context: .
      dockerfile: ./dockerfiles/php.dockerfile
    volumes:
      - /var/www/html/vendor
      - ./:/var/www/html
      - ./storage/logs:/var/www/html/storage/logs
    networks:
      - ptd-network
    extra_hosts:
        - "host.docker.internal:host-gateway"
  node:
    build:
      context: .
      dockerfile: ./dockerfiles/node.production.dockerfile
    volumes:
      - ./:/var/www/html
      - /var/www/html/node_modules

volumes:
  ptd-db:

networks:
  ptd-network:
    driver: bridge
